[package]
name = "pdf-trust-anchors"
version = "0.1.0"
edition = "2021"

[dependencies]
static_prefs = { path = "../../../../modules/libpref/init/static_prefs" }
thin-vec = { version = "0.2.1", features = ["gecko-ffi"] }

[build-dependencies]
trust-anchor-build-util = { path = "../trust-anchor-build-util" }
