[[repos]]
name = 'spec'
commit = '6e4c4bcaf'

[[repos]]
name = 'threads'
commit = '3635ca51a'

[[repos]]
name = 'custom-page-sizes'
commit = 'cad80dc2c'

[[repos]]
name = 'compact-import-section'
commit = 'bebcdeff9'
